#/etc/dnsmasq.conf

# block incomplete requests from leaving your network
domain-needed 

# prevent non-routable private addresses from being forwarded out of your network.
bogus-priv

domain=csc.dmu.test

# add the domain name to your hostnames, so you get fully-qualified domain names such as hostname.csc.dmu.test
expand-hosts

# ensure that queries for your private domain are only answered by Dnsmasq or from /etc/hosts
local=/csc.dmu.test/

# tell dnsmasq which interface or interfaces to listen on
listen-address=127.0.0.1 
listen-address=10.227.150.220

# ensure that Dnsmasq will listen only to the addresses specified with listen-address
bind-interfaces

