# dhcpd.conf
# Sample configuration file for CTEC1704 - Internet Protocols
# Kathara ISC DHCP server

ddns-update-style none;

# This DHCP server should send DHCPNAK messages to misconfigured clients.
authoritative;

# Subnet declaration for the 172.16.12.0/24 network.
subnet 172.16.12.0 netmask 255.255.255.0
{
    range 172.16.12.65 172.16.12.150;
    option subnet-mask 255.255.255.0;
    option broadcast-address 172.16.12.255;
    option routers 172.16.12.254;
    get-lease-hostnames true;
    use-host-decl-names true;
    default-lease-time 30;
    max-lease-time 60;
}
