LAB_DESCRIPTION="A simple client server network to demonstrate the creation and usage of SSL certificates"
LAB_VERSION=1.0
LAB_AUTHOR="C Ingrams"
LAB_EMAIL="cfi@dmu.ac.uk"
LAB_WEB=""

ssl_client[0]=lan
ssl_server[0]=lan
