LAB_DESCRIPTION="A Kathara lab to configure, use, capture, and analyse DHCP"
LAB_VERSION=1.0
LAB_AUTHOR="C Ingrams"
LAB_EMAIL=cfi@dmu.ac.uk

dhcp_client_1[0]=lan
dhcp_client_1[image]="lab17-dhcp:latest"
dhcp_client_2[0]=lan
dhcp_client_2[image]="lab17-dhcp:latest"
dhcp_server[0]=lan
dhcp_server[mem]=512
dhcp_server[image]="lab17-dhcp:latest"
